# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  App_config = debug
  Opengl_Core_config = debug

else ifeq ($(config),release)
  App_config = release
  Opengl_Core_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := App Opengl-Core

.PHONY: all clean help $(PROJECTS) App Opengl-Core

all: $(PROJECTS)

App: App

Opengl-Core: Opengl-Core

App: Opengl-Core
ifneq (,$(App_config))
	@echo "==== Building App ($(App_config)) ===="
	@${MAKE} --no-print-directory -C App -f Makefile config=$(App_config)
endif

Opengl-Core:
ifneq (,$(Opengl_Core_config))
	@echo "==== Building Opengl-Core ($(Opengl_Core_config)) ===="
	@${MAKE} --no-print-directory -C Opengl-Core -f Makefile config=$(Opengl_Core_config)
endif

clean:
	@${MAKE} --no-print-directory -C App -f Makefile clean
	@${MAKE} --no-print-directory -C Opengl-Core -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   App"
	@echo "   Opengl-Core"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"